sonar.organization=ledloy
sonar.projectKey=qa-auto-engineer-javascript-project-87
sonar.sources=src
sonar.tests=__tests__
sonar.inclusions=src/**/*.js,__tests__/**/*.js
sonar.exclusions=**/node_modules/**,**/__fixtures__/**,**/*.config.js
sonar.test.inclusions=__tests__/**/*.test.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.testExecutionReportPaths=coverage/sonar-report.xml
sonar.sourceEncoding=UTF-8